version: "3.0"
services:
  envoy-stat:
    image: envoyproxy/envoy:v1.19-latest
    command: [ "envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info" ]
    ports:
      - "9901:9901"
      - "9902:9902"
      - "8000:8000"
      - "10001:10001"
      - "10000:10000"
    volumes:
      - ./local-rate-limit-with-descriptors.yaml:/etc/envoy/envoy.yaml
  service:
    image: nginx@sha256:4ed64c2e0857ad21c38b98345ebb5edb01791a0a10b0e9e3d9ddde185cdbd31a